ALTER TABLE "rentals" ADD COLUMN "isTest" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "messages" ADD COLUMN "isTest" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "car_seat_requests" ADD COLUMN "isTest" BOOLEAN NOT NULL DEFAULT false;
